package com.liu.Entity;
// Generated 2017-7-10 19:35:37 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.GenericGenerator;

/**
 * Business generated by hbm2java
 * Business : people who sell products
 */
@Entity
@Table(name = "business", catalog = "project", uniqueConstraints = @UniqueConstraint(columnNames = "nick_name"))
public class Business implements java.io.Serializable {

	/**
	 * 属性
	 */
	private static final long serialVersionUID = 180381899242596825L;	//序列号
	private String id;				//商家ID
	private String nickName;		//昵称
	private String username;		//用户名
	private String password;		//密码
	private String telephone;		//手机号
	private String imgurl;			//图片的地址
	private Date openDate;			//开店日期
	private String memo;			//商家描述
	private Set<Products> productses = new HashSet<Products>(0);	//商家上架的商品
	private Set<Order> order = new HashSet<Order>(0);				//商家的订单

	public Business() {
	}

	public Business(String id, String nickName, String username, String password, String telephone, Date openDate) {
		this.id = id;
		this.nickName = nickName;
		this.username = username;
		this.password = password;
		this.telephone = telephone;
		this.openDate = openDate;
	}

	public Business(String id, String nickName, String username, String password, String telephone, String imgurl,
			Date openDate, String memo, Set<Products> productses) {
		this.id = id;
		this.nickName = nickName;
		this.username = username;
		this.password = password;
		this.telephone = telephone;
		this.imgurl = imgurl;
		this.openDate = openDate;
		this.memo = memo;
		this.productses = productses;
	}

	@Id
	@GeneratedValue(generator = "uuid")
	@GenericGenerator(name = "uuid", strategy = "uuid")
	@Column(name = "id", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "nick_name", unique = true, nullable = false, length = 45)
	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	@Column(name = "username", nullable = false, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "telephone", length = 45)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "imgurl", length = 200)
	public String getImgurl() {
		return this.imgurl;
	}

	public void setImgurl(String imgurl) {
		this.imgurl = imgurl;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "open_date", nullable = false, length = 10)
	public Date getOpenDate() {
		return this.openDate;
	}

	public void setOpenDate(Date openDate) {
		this.openDate = openDate;
	}

	@Column(name = "memo", length = 200)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "business")
	@OrderBy("onselldate ASC")
	public Set<Products> getProductses() {
		return this.productses;
	}

	public void setProductses(Set<Products> productses) {
		this.productses = productses;
	}
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "business")
	@OrderBy("date ASC")
	public Set<Order> getOrder() {
		return order;
	}
	
	public void setOrder(Set<Order> order) {
		this.order = order;
	}


}
