package com.liu.Entity;
// Generated 2017-7-10 19:35:37 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.GenericGenerator;

/**
 * Customer generated by hbm2java
 * Customer ：people who buy products
 */
@Entity
@Table(name = "customer", catalog = "project", uniqueConstraints = @UniqueConstraint(columnNames = "nickname"))
public class Customer implements java.io.Serializable {

	/**
	 * 属性
	 */
	private static final long serialVersionUID = 3992376887476377L;	//序列号
	private String id;			//买家ID号
	private String nickname;	//昵称
	private String username;	//用户名
	private String password;	//密码
	private String telephone;	//手机号
	private String imgurl;		//头像路径
	private String location;	//收货地址
	private Set<Order> orders = new HashSet<Order>(0);	//买家的订单

	public Customer() {
	}

	public Customer(String id, String nickname, String username, String password, String telephone, String location) {
		this.id = id;
		this.nickname = nickname;
		this.username = username;
		this.password = password;
		this.telephone = telephone;
		this.location = location;
	}

	public Customer(String id, String nickname, String username, String password, String telephone, String imgurl,
			String location, Set<Order> orders) {
		this.id = id;
		this.nickname = nickname;
		this.username = username;
		this.password = password;
		this.telephone = telephone;
		this.imgurl = imgurl;
		this.location = location;
		this.orders = orders;
	}

	@Id

	@GeneratedValue(generator = "uuid")
	@GenericGenerator(name = "uuid", strategy = "uuid")
	@Column(name = "id", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "nickname", unique = true, nullable = false, length = 45)
	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	@Column(name = "username", nullable = false, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "telephone", length = 45)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "imgurl", length = 45)
	public String getImgurl() {
		return this.imgurl;
	}

	public void setImgurl(String imgurl) {
		this.imgurl = imgurl;
	}

	@Column(name = "location", length = 45)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

}
