package com.liu.Entity;
// Generated 2017-7-10 19:35:37 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id 

;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name = "products", catalog = "project")
public class Products implements java.io 

.Serializable {

	/**
	 * 属性
	 */
	private static final long serialVersionUID = -8957099613214190183L;
	private String id;  	   	//商品id
	private Business business;	//上架此商品的商家
	private String name;       	//商品名称 
	private String type;		//商品类型
	private String imgurl;		//商品图片地址
	private double price;		//商品单价
	private String memo;		//商品描述
	private int instock;		//商品库存
	private int selled;			//已售数量
	private Date onselldate;	//上架日期
	private Set<Order> orders = new HashSet<Order>(0);

	public Products() {
	}

	public Products(String id, Business business, String name, String type, String imgurl, double price, String memo,
			int instock, int selled, Date onselldate) {
		this.id 

 = id;
		this.business = business;
		this.name 

 = name;
		this.type = type;
		this.imgurl = imgurl;
		this.price = price;
		this.memo = memo;
		this.instock = instock;
		this.selled = selled;
		this.onselldate = onselldate;
	}

	public Products(String id, Business business, String name, String type, String imgurl, double price, String memo,
			int instock, int selled, Date onselldate, Set<Order> orders) {
		this.id 

 = id;
		this.business = business;
		this.name 

 = name;
		this.type = type;
		this.imgurl = imgurl;
		this.price = price;
		this.memo = memo;
		this.instock = instock;
		this.selled = selled;
		this.onselldate = onselldate;
		this.orders = orders;
	}

	@Id
	@GeneratedValue(generator = "uuid")
	@GenericGenerator(name = "uuid", strategy = "uuid")

	@Column(name = "id", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id 

;
	}

	public void setId(String id) {
		this.id 

 = id;
	}

	@JsonIgnoreProperties(value={"products","orders"})
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "businessid", nullable = false)
	public Business getBusiness() {
		return this.business;
	}

	public void setBusiness(Business business) {
		this.business = business;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name 

;
	}

	public void setName(String name) {
		this.name 

 = name;
	}

	@Column(name = "type", nullable = false, length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "imgurl", nullable = false, length = 200)
	public String getImgurl() {
		return this.imgurl;
	}

	public void setImgurl(String imgurl) {
		this.imgurl = imgurl;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Column(name = "memo", nullable = false, length = 45)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Column(name = "instock", nullable = false)
	public int getInstock() {
		return this.instock;
	}

	public void setInstock(int instock) {
		this.instock = instock;
	}

	@Column(name = "selled", nullable = false)
	public int getSelled() {
		return this.selled;
	}

	public void setSelled(int selled) {
		this.selled = selled;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "onselldate", nullable = false, length = 10)
	public Date getOnselldate() {
		return this.onselldate;
	}

	public void setOnselldate(Date onselldate) {
		this.onselldate = onselldate;
	}

	@JsonIgnoreProperties(value={"business", "customer","products"})
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "products")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

}